// Date: 01/10/2013 20:00:25
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package gaarnik.bsa.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ElevatorModel extends ModelBase {
	// *******************************************************************

	// *******************************************************************
	private ModelRenderer Shape1;

	// *******************************************************************
	public ElevatorModel() {
		textureWidth = 64;
		textureHeight = 32;

		Shape1 = new ModelRenderer(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 16, 16);
		Shape1.setRotationPoint(-8F, 8F, -8F);
		Shape1.setTextureSize(64, 32);
		Shape1.mirror = true;
		
		this.setRotation(Shape1, 0F, 0F, 0F);
	}

	// *******************************************************************
	/*public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		/*super.render(entity, f, f1, f2, f3, f4, f5);
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		
		//Shape1.render(f5);
		Shape1.render(0.0625F);
	}*/
	
	public void renderElevator() {
		this.Shape1.render(0.0625F);
	}
	
	// *******************************************************************
	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

}
